version: '3.8'

services:
  backend:
    build: ./apps/api
    container_name: nest-backend
    ports:
      - '3001:3001'
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      OPENAI_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - ./apps/api:/app

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - '6379:6379'

volumes:
  db_data:
